---
name: Test or run Terraform code
description: Easily integrate tests into your GitHub workflow.
author: Robert de Bock <robert@meinit.nl>

inputs:
  action:
    description: |
      The command to run.
      For example: `validate` (default), `init`, `plan` or `apply`.
    required: true
    default: init
  directory:
    description: |
      The directory where the Terraform files can be found.
      This defaults to `./`, but can be set to i.e. `./example`.
    required: true
    default: ./
runs:
  using: docker
  image: 'docker://hashicorp/terraform:1.0.0'
  args:
    - -chdir=${{ inputs.directory }} ${{ inputs.action }}

branding:
  icon: user-check
  color: black
